crl_urls = [
    "https://crl.boeing.com/crl/Boeing%20PCA%20G2.crl",
    "https://crl.boeing.com/crl/Boeing%20SecureBadge%20Medium%20G2.crl",
    "https://crl.boeing.com/crl/Boeing%20PCA%20G3.crl",
    "https://crl.boeing.com/crl/Boeing%20Medium%20Assurance%20Hardware%20Issuing%20CA%20G3.crl",
    "https://crl.external.lmco.com/crl/certupd/Lockheed%20Martin%20Root%20Certification%20Authority.crl",
    "https://crl.external.lmco.com/crl/certupd/Lockheed%20Martin%20Root%20Certification%20Authority%202.crl",
    "https://crl.external.lmco.com/crl/certupd/Lockheed%20Martin%20US%20Certification%20Authority-2.crl",
    "https://crl.external.lmco.com/crl/certupd/Lockheed%20Martin%20Certification%20Authority%204%20G2.crl",
    "https://crl.external.lmco.com/crl/certupd/Lockheed%20Martin%20Certification%20Authority%206%20G3.crl",
    "https://crl.external.lmco.com/crl/certupd/Lockheed%20Martin%20Root%20Certification%20Authority%206.crl",
    "http://certdata.northropgrumman.com/certdata/Northrop%20Grumman%20Corporation%20Root%20CA.crl",
    "http://certdata.northropgrumman.com/certdata/crls/RevokedByNorthropGrummanCorporateRootCA-G2.crl",
    "http://certdata.northropgrumman.com/certdata/Northrop%20Grumman%20Corporation%20Issuing%20CA%202.crl",
    "http://certdata.northropgrumman.com/certdata/crls/RevokedByNorthropGrummanCorporateSigningCA-G2.crl",
    "http://certdata.northropgrumman.com/certdata/crls/RevokedByNorthropGrummanCorporateRootCA-384.crl",
    "http://certdata.northropgrumman.com/certdata/crls/RevokedByNorthropGrummanCorporateSigningCA-384.crl",
    "https://pki.raytheon.com/G2/CRLs/Raytheon_Root-G2_Full.crl",
    "https://pki.raytheon.com/G2/CRLs/Raytheon_services-G2Full.crl",
    "http://http.fpki.gov/fcpca/fcpca.crl",
    "https://crl-server.orc.com/CRLs/ORCSSP3.crl",
    "https://repo.fpki.gov/bridge/fbcag4.crl",
    "https://repo.fpki.gov/fcpca/fcpcag2.crl",
    "https://eca.orc.com/CRLs/ORCECA7.crl",
    "https://crl.gds.disa.mil/getcrlzip?ALL+CRL+ZIP"

]